# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- PipeTesty

pool:
  vmImage: ubuntu-latest

steps:
- task: UnitySetupTask@2

- task: UnityBuildTask@3
  inputs:
    buildTarget: 'Web'
    unityProjectPath: '$(System.DefaultWorkingDirectory)/'
    versionSelectionMode: 'project'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'drop'